 ---
    name: Bug Report
    about: Submit a bug report to help us improve
    title: "[Bug]: "
    assignees: ["mtarsel", "mjturek", "my-team"]
    labels: ["bug", "needs-triage"]
    ---

    **Describe the bug**
    [Describe the bug in detail here.]

    **To Reproduce**
    [Steps to reproduce the behavior.]

    **Expected behavior**
    [A clear and concise description of what you expected to happen.]

    **Screenshots**
    [If applicable, add screenshots to help explain your problem.]
